project scrum updates
vertelab/odoo-project_scrum pull request #25
Opened 2021-08-30 15:19 UTC by iammiracle

2021-08-30 16:14 UTC, fredrikarvas-vertel approved these changes
This is ok to test on the server now.

2021-08-31 06:36 UTC, daerio requested changes
can you clean up these lines please?

2021-08-31 06:36 UTC, daerio commented on project_scrum/wizard/project_scrum_test_task_view.xml
> +<!--            <field name="view_mode">form</field>-->
delete

2021-08-31 06:36 UTC, daerio commented on project_scrum/wizard/project_scrum_test_task_view.xml
>  <!--            <field name="menu_ir_values_id" ref="ps_make_test_task"/>-->
delete

2021-08-31 06:36 UTC, daerio commented on project_scrum/models/project_scrum.py
> +
delete

2021-08-31 06:36 UTC, daerio commented on project_scrum/models/project_scrum.py
delete

2021-08-31 06:46 UTC, daerio approved these changes

2021-08-31 06:47 UTC, merged